apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: bWV1YmFuY28=            # "meubanco" em Base64
  POSTGRES_USER: dXN1YXJpbw==           # "usuario" em Base64
  POSTGRES_PASSWORD: c2VuaGE=           # "senha" em Base64